version: "3.5"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./a.env
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

  # postgres_admin2:
  #    image: dpage/pgadmin4:6.16
  #    depends_on: 
  #      - postgres
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: marc@arza.com
  #      PGADMIN_DEFAULT_PASSWORD: 1234
  #    ports:
  #      - 5050:80
  #    networks:
  #      - backend

  backend:
    build:
      context: ./src/backend
    ports:
      - 3000:3000
    networks:
      - backend
    volumes:
      - ./src/backend:/backend
      - ./avatars:/app/src/uploads/avatar/
      - '/backend/node_modules'
    env_file:
      - ./a.env
    restart: unless-stopped
    depends_on:
      - postgres
    command: npm run start:dev

  frontend:
    build:
      context: ./src/frontend
    ports:
      - 80:4200
    networks:
      - backend
    volumes:
      - ./src/frontend:/frontend
      - '/frontend/node_modules'
    env_file: 
      - ./a.env
    environment:
        - CHOKIDAR_USEPOLLING=true
    command: ng serve --host 0.0.0.0 --disable-host-check
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  backend:
  data:
  avatars:

networks:
  backend:


# version: "3.5"

# services:
#   postgres:
#     image: postgres:latest
#     env_file:
#       - ./a.env
#     restart: unless-stopped
#     volumes:
#       - data:/var/lib/postgresql/data
#     ports:
#       - 5432:5432
#     networks:
#       - backend

#   postgres_admin2:
#      image: dpage/pgadmin4:6.16
#      depends_on: 
#        - postgres
#      environment:
#        PGADMIN_DEFAULT_EMAIL: marc@arza.com
#        PGADMIN_DEFAULT_PASSWORD: rielf222
#      ports:
#        - 5050:80
#      networks:
#        - backend

#   backend:
#     build: ./src/backend
#     ports:
#       - 3000:3000
#     networks:
#       - backend
#     volumes:
#       - backend:/transcendence/backend
#       - ./backend:/transcendence/src/backend/
#       - ./avatars:/app/src/uploads/avatar/
#     env_file:
#       - ./a.env
#     restart: unless-stopped
#     depends_on:
#       - postgres

#   frontend:
#     build:
#       context: ./src/frontend
#       dockerfile: Dockerfile
#     ports:
#       - 80:4200
#     networks:
#       - backend
#     volumes:
#       - ./src/frontend:/home/transcendance/src/frontend
#     env_file:
#       - ./a.env
#     restart: unless-stopped
#     depends_on:
#       - backend

# volumes:
#   backend:
#   data:
#   avatars:

# networks:
#   backend: