version: "3.5"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./a.env
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

  postgres_admin2:
     image: dpage/pgadmin4:6.16
     depends_on: 
       - postgres
     environment:
       PGADMIN_DEFAULT_EMAIL: marc@arza.com
       PGADMIN_DEFAULT_PASSWORD: rielf222
     ports:
       - 5050:80
     networks:
       - backend

  backend:
    build: ./src/backend
    ports:
      - 3000:3000
    networks:
      - backend
    volumes:
      - backend:/home/transcendence/backend
      - ./avatars:/app/src/uploads/avatar/
    env_file:
      - ./a.env
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    build: ./src/frontend
    ports:
      - 80:4200
    networks:
      - backend
    volumes:
      - ./frontend:/app
    env_file:
      - ./a.env
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  backend:
  data:
  avatars:

networks:
  backend: